[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Add your Firebase environment variables here as backup
  # Replace these placeholder values with your actual Firebase credentials
  REACT_APP_FIREBASE_API_KEY = "your-actual-api-key"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "your-project-id"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "your-sender-id"
  REACT_APP_FIREBASE_APP_ID = "your-app-id"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "your-measurement-id" 